// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudentsApi.Data;

#nullable disable

namespace StudentsApi.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250709180000_InitialCreate")]
partial class InitialCreate
{
}
