// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StudentsApi.Data;

#nullable disable

namespace StudentsApi.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

        modelBuilder.Entity("StudentsApi.Models.StudentProject", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("ApprovedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("ApprovedBy").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("AuthorName").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("AuthorSub").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Description").IsRequired().HasColumnType("text");
            b.Property<string>("Features").IsRequired().HasColumnType("jsonb");
            b.Property<string>("GithubUrl").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("LiveUrl").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("RejectionReason").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("Tagline").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<string>("TechStack").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("AuthorSub");
            b.HasIndex("Status");
            b.ToTable("student_projects", (string)null);
        });

        modelBuilder.Entity("StudentsApi.Models.StudentProjectMedia", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("ProjectId").HasColumnType("uuid");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.Property<string>("StorageKey").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("Type").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("Url").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.HasKey("Id");
            b.HasIndex("ProjectId");
            b.ToTable("student_project_media", (string)null);
        });

        modelBuilder.Entity("StudentsApi.Models.StudentProjectMedia", b =>
        {
            b.HasOne("StudentsApi.Models.StudentProject", "Project")
                .WithMany("Media")
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Project");
        });

        modelBuilder.Entity("StudentsApi.Models.StudentProject", b =>
        {
            b.Navigation("Media");
        });
#pragma warning restore 612, 618
    }
}
